config/routes.rb
Treebook::Application.routes.draw do
  get "profiles/show"

  devise_scope :user do
  get 'sign_up', to: 'devise/registrations#new', as: :registration
  get 'sign_in', to: 'devise/sessions#new', as: :login
  get 'sign_out', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed

  root to: 'statuses#index'

  get '/:id', to: 'profiles#show'

end

app/models/status.rb
class Status < ActiveRecord::Base
  #attr_accessible :content, :user_id
  belongs_to :user

  validates :content, presence: true, #part of activeRecord validation
                      length: {minimum: 2}
  validates :user_id, presence: true #part of activeRecord validation
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, presence: true #part of activeRecord validation

  validates :last_name, presence: true #part of activeRecord validation

  validates :profile_name, presence: true,
                           uniqueness: true,
                           format: {
                             with: /\A[a-zA-Z0-9_-]+\z/,
                             message: 'Must be formatted correctly.'
                           }


  has_many :statuses
  def full_name
    first_name+ " " + last_name
  end

  def gravatar_url
    stripped_email = email.strip
    downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)

    "http://gravatar.com/avatar/#{hash}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :warning
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) do |u|
      u.permit(:profile_name, :email, :password, :first_name, :last_name, :avatar)
    end

    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:email, :password, :password_confirmation,
               :remember_me, :first_name, :last_name, :profile_name, :full_name, :avatar)
    end

    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:email, :password, :password_confirmation, :current_password,
               :remember_me, :first_name, :last_name, :profile_name, :full_name, :avatar)
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    #instance variable are available to controller and views..params hash is sent in by web browser with id parameter

    @user = User.find_by_profile_name(params[:id])

    # I know i know if..else..end read better.
    unless @user
      render file: 'public/404', status: 404, formats: [:html] #when rails cant find, render 404 with 404 status
    else
      # we will use scoping(@__) to get only user's statuses instead of all statuses, we have association relation user.hasmany.statuses
      @statuses = @user.statuses.to_a #below is how it should be..but just let it goo...to_a is lazy loading (statuses.load works too)
      #@statuses = @user.statuses.order('created_at DESC').limit(5).to_a
      render action: :show
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
 before_action :set_status, only: [:show, :edit, :update, :destroy]
#   https://github.com/plataformatec/devise#controller-filters-and-helpers ,only for new posts
before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params) #bugsy
    #@status = current_user.statuses.new(status_params) correct one 
    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class (type)
    case type
    when :alert
      "alert-danger"
    when :notice
      "alert-success"
    when :warning
      "alert-warning"
    else
      ""
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
      <a class="navbar-brand" href="#"> Treebook </a>
      <ul class="nav navbar-nav">
        <li> <%= link_to "All Statuses", feed_path %> </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.full_name %><span class="caret"></span></a>
            <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", logout_path %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Sign up", registration_path%></li>
        <li><%= link_to "Login", login_path%></li>
        <% end %>
      </ul>
  </div>

</nav>

<div class="container-fluid">
  <% flash.each do |type, message| %>
  <div class="alert <%= flash_class type %>" role="alert">
  <%= message %>
  </div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
  <h1><%= @user.full_name %></h1>
</div>

<% if @statuses %>
  <% @statuses.each do |status| %>
    <div class="well well-sm">
      <%= status.content %>
      <hr />
      <%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
    </div>
  <% end %>
<% end %>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-vertical"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="form-group">
  <%= f.input :user_id, collection: User.all, label_method: :full_name %>
  <%= f.input :content %>
  <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
<h1> Status Feed </h1>
</div>
<%= link_to 'Post a New Status', new_status_path, class: "btn btn-success"%>
<% @statuses.each do |status| %>
<div class="container-fluid">
  <div class="status">
    <div class="row">
      <div class="col-md-1">
        <%= image_tag status.user.gravatar_url %> 
      </div>
      <div class="col-md-7">
        <strong> <%= status.user.full_name %></strong>
          <p><%= status.content %></p>
          <div class="meta">
            <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
            <span class="admin">
              | <%= link_to 'Edit', edit_status_path(status) %> |
              <%= link_to 'Delete', status, method: :delete, data: { confirm: 'Are you sure?' } %>
            </span>
          </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @status.user.full_name %>

</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>